# Generated by Django 4.0.4 on 2022-07-02 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='user_id',
            field=models.IntegerField(default=353057906, unique=True, verbose_name='Ідентифікатор користувача у телеграмі'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(default=353057906, unique=True, verbose_name='Ідентифікатор користувача у телеграмі'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='telegram_id', verbose_name='Користувач'),
        ),
    ]
