# Generated by Django 4.0.4 on 2022-07-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_referral_user_id_user_telegram_id_alter_referral_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_name',
            field=models.CharField(max_length=50, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.CharField(max_length=250, verbose_name='Фото file_id'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory_name',
            field=models.CharField(max_length=50, verbose_name='Назва підкатегорії'),
        ),
    ]
