# Generated by Django 4.0.4 on 2022-07-07 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_item_category_name_alter_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category_name',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='Не визначено', on_delete=django.db.models.deletion.CASCADE, to='administration.category', to_field='name', verbose_name='Категорія'),
        ),
    ]
