# Generated by Django 4.0.4 on 2022-07-07 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_category_remove_item_category_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory_name',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.category', to_field='name', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Підкатегорія',
                'verbose_name_plural': 'Підкатегорії',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(default='Перші страви', on_delete=django.db.models.deletion.CASCADE, to='administration.subcategory', to_field='name', verbose_name='Підкатегорія'),
        ),
    ]
