# Generated by Django 4.0.4 on 2022-06-27 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.uuid1, max_length=100, unique=True, verbose_name="Ім'я користувача в телеграмі"),
        ),
    ]
