# Generated by Django 4.0.4 on 2022-06-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name="Ім'я користувача в телеграмі"),
        ),
    ]
