# Generated by Django 4.0.4 on 2022-07-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_orderitem_item_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address_latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
