# Generated by Django 4.0.4 on 2022-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_order_shipping_address_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
