# Generated by Django 4.0.4 on 2022-07-27 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_alter_order_shipping_address_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.restaurant'),
        ),
    ]
