# Generated by Django 4.0.4 on 2022-07-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_order_shipping_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_chef',
            field=models.BooleanField(default=False, verbose_name='Шеф'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_courier',
            field=models.BooleanField(default=False, verbose_name="Кур'єр"),
        ),
    ]
