# Generated by Django 4.0.4 on 2022-07-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_user_connected_restaurant_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
