# Generated by Django 4.0.4 on 2022-08-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_alter_orderitem_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_price',
        ),
    ]
