# Generated by Django 4.0.4 on 2022-08-28 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_alter_order_options_remove_order_tax_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Замовник'),
        ),
    ]
