# Generated by Django 4.0.4 on 2022-09-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_alter_order_shipping_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AddField(
            model_name='user',
            name='referred',
            field=models.IntegerField(default=0, verbose_name='К-сть людей, що використали його реферал'),
        ),
    ]
