# Generated by Django 4.0.4 on 2022-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0027_alter_order_options_user_referred'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
