# Generated by Django 4.0.4 on 2022-09-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0028_referral_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Активований'),
        ),
    ]
