# Generated by Django 4.1.7 on 2023-07-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0030_order_is_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Фото"
            ),
        ),
    ]
