# TODO: testing all situations
from . import (admin,
               callbacks,
               help,
               start,
               support,
               support_call,
               purchase,
               menu,
               item,
               user,
               location,
               payments,
               echo,
               errors)
